config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profiles/home'
  get 'profiles/edit'
  get 'profiles/update'
  get 'help/index'
  root to: 'players#index'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  resources :players
  resources :permissions
  resources :permission_users
  resources :images
  resources :events

  get 'profiles/home'
  get 'profiles/edit'
  post 'profiles', to: 'profiles#update', as: :update_profile
  delete 'admins/:admin_id', to: 'admins#destroy', as: :destroy_admin

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/permission.rb
# frozen_string_literal: true

class Permission < ApplicationRecord
  # description cannot have any special characters besides '-' and '_' and spaces
  validates :description, presence: true,
                          format: {
                            with: /\A[A-Za-z\d\-_ ]*\z/,
                            message: "cannot use any special characters other than spaces, '-' (dashes), or '_' (underscores)"
                          }
  has_many :user_permissions, class_name: 'PermissionUser', foreign_key: 'permissions_id_id', dependent: :destroy, inverse_of: :permissions_id

  def self.admin_permission?(cur_perm)
    cur_perm.description == 'admin'
  end

  def self.exist?(cur_perm)
    !cur_perm.nil?
  end
end

app/controllers/permissions_controller.rb
# frozen_string_literal: true

class PermissionsController < ApplicationController
  before_action :set_permission, only: %i[show edit update destroy]

  # GET /permissions or /permissions.json
  def index
    @permissions = Permission.all
  end

  # GET /permissions/1 or /permissions/1.json
  def show; end

  # GET /permissions/new
  def new
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit; end

  # POST /permissions or /permissions.json
  def create
    @permission = Permission.new(permission_params)
    respond_to do |format|
      if @permission.save
        format.html { redirect_to(@permission, notice: 'Permission was successfully created.') }
        format.json { render(:show, status: :created, location: @permission) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @permission.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /permissions/1 or /permissions/1.json
  def update
    respond_to do |format|
      if @permission.update(permission_params)
        format.html { redirect_to(@permission, notice: 'Permission was successfully updated.') }
        format.json { render(:show, status: :ok, location: @permission) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @permission.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /permissions/1 or /permissions/1.json
  def destroy
    @permission.destroy!
    respond_to do |format|
      format.html { redirect_to(permissions_url, notice: 'Permission was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_permission
    @permission = Permission.where(id: params[:id]).first
  end

  # Only allow a list of trusted parameters through.
  def permission_params
    params.require(:permission).permit(:description)
  end
end

app/helpers/permissions_helper.rb
# frozen_string_literal: true

module PermissionsHelper
end

app/views/permissions/_back.html.erb
<form class="button_to" method="get" action=<%= permissions_path %>>
  <button class="btn back-button" id="back">
    <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-left-short back-button" viewbox="0 0 16 16">
      <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
    </svg>
    <span class="back-button">Back</span>
  </button>
</form>

app/views/permissions/_form.html.erb
<%= form_with(model: permission) do |form| %>
<% if permission.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(permission.errors.count, "error") %>
      prohibited this permission from being saved:</h2>

    <ul>
      <% permission.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group">
  <%= form.label :description, class: 'form-label' %>
  <%= form.text_field :description, class: 'form-control', rows: '3', placeholder: 'Enter Permission Description'%>
</div>

<br>
<button type='submit' class='btn btn-new'>Submit</button>
<% end %>

app/views/permissions/edit.html.erb
<% if Permission.exist?(@permission) && !Permission.admin_permission?(@permission) && Admin.current_user_admin?(current_admin) %>
  <div class="container show-container">
    <div class="container page-top-margin">
      <%= render 'back'%>
    </div>
    <div class="container text-center">
      <h1>
        Editing
        <%= @permission.description%>
      </h1>
    </div>

    <div class="container form-bottom-padding justify-content-center">
      <%= render 'form', permission: @permission %>
    </div>
  </div>
<% else %>
  <%= render 'layouts/permission_denied'%>
<% end %>

app/views/permissions/index.html.erb
<% if Admin.current_user_admin?(current_admin)%>
  <div class="container flex-column align-items-center show-container" style="padding-top: 80px;">
    <%= render 'permission_users/back'%>
  </div>
  <div class="d-flex justify-content-center flex-column align-items-center" style="padding-top: 80px;">
    <div class="text-center">
      <h1>Permissions</h1>
      <%= button_to "Add a New Permission", new_permission_path, class: 'btn btn-new', :method => :get%>
    <div>

    <br/>

    </div>
      <table class="table table-striped table-bordered table-responsive table-font">
        <thead class="thead-light">
          <tr>
            <th scope="col">Description</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @permissions.each do |permission|%>
            <tr class="center-vert-hor cell-pad">
              <td>
                <form class="button_to" method="get" action=<%= permission_path(permission) %>>
                  <button class="btn" id="permission-<%= permission.id %>">
                    <span style="font-weight: bold"><%= permission.description %></span>
                  </button>
                </form>
              </td>
              <td>
                <% if permission.description != 'admin'%>
                  <div class="d-flex center-vert-hor actions">
                    <form class="button_to" method="get" action=<%= edit_permission_path(permission)%>>
                      <button class="btn" id="edit-permission-<%= permission.id %>">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil edit" viewbox="0 0 16 16">
                          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                        </svg>
                      </button>
                    </form>
                    <br><br>
                    <a data-method="delete" href="/permissions/<%= permission.id%>" data-confirm="Are you sure you want to delete all of <%= permission.description %>'s data? This action is irreversible!" class="delete" id="delete-permission-<%= permission.id %>">
                      <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash delete" viewbox="0 0 16 16">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                      </svg>
                    </a>
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <br>

  </div>
<% else %>
  <%= render 'layouts/permission_denied'%>
<% end %>

app/views/permissions/new.html.erb
<% if Admin.current_user_admin?(current_admin)%>
  <div class="container show-container">
    <div class="container page-top-margin">
      <%= render 'back'%>
    </div>
    <div class="container text-center">
      <h1>
        New Permission
      </h1>
    </div>
    <div class="container form-bottom-padding justify-content-center">
      <%= render 'form', permission: @permission %>
    </div>
  </div>
<% else %>
  <%= render 'layouts/permission_denied'%>
<% end %>

app/views/permissions/show.html.erb
<% if Permission.exist?(@permission) && Admin.current_user_admin?(current_admin)%>
  <p id="notice"><%= notice %></p>
  <div class="container show-container">
    <div class="container page-top-margin">
      <%= render 'back'%>
    </div>
    <br/>
    <div class="text-center">
      <h1>Description</h1>
    </div>

    <!-- Edit/Delete buttons -->
    <% if @permission.description != 'admin'%>
      <div class="d-flex center-vert-hor actions justify-content-center">
        <form class="button_to" method="get" action=<%= edit_permission_path(@permission)%>>
          <button class="btn" id="edit-permission-<%= @permission.id %>">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil edit" viewbox="0 0 16 16">
              <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
            </svg>
          </button>
        </form>
        <br><br>
        <a data-method="delete" href="/permissions/<%= @permission.id%>" data-confirm="Are you sure you want to delete all of <%= @permission.description %>'s data? This action is irreversible!" class="delete" id="delete-permission-<%= @permission.id %>">
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash delete" viewbox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg>
        </a>
      </div>
    <% end %>

    <div class="text-center">
      <div>
        <%= @permission.description %>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'layouts/permission_denied'%>
<% end %>