config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profiles/home'
  get 'profiles/edit'
  get 'profiles/update'
  get 'help/index'
  root to: 'players#index'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  resources :players
  resources :permissions
  resources :permission_users
  resources :images
  resources :events

  get 'profiles/home'
  get 'profiles/edit'
  post 'profiles', to: 'profiles#update', as: :update_profile
  delete 'admins/:admin_id', to: 'admins#destroy', as: :destroy_admin

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/player.rb
# frozen_string_literal: true

# https://api.rubyonrails.org/v5.1.7/classes/ActiveModel/Validations/ClassMethods.html
class Player < ApplicationRecord
  belongs_to :admin

  validates :admin_id, :name, :losses, :wins, presence: true

  # name cannot have any special characters besides '-' and '_' and spaces
  validates :name,
            format: {
              with: /\A[A-Za-z\d\-_ ]*\z/,
              message: "Cannot use any special characters other than spaces, '-' (dashes), or '_' (underscores)"
            }

  # played & wins needs to be a positive integer that is within integer bounds
  validates :losses, :wins, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2_147_483_647,
    message: 'values must be between 0 and 2,147,483,647'
  }

  def self.allowed_to_show?(current_admin, player_querying)
    !player_querying.nil? && Admin.id(current_admin).equal?(player_querying.admin_id)
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :set_player, only: %i[show edit update destroy]

  # GET /players or /players.json
  def index
    # @players = Player.where(admin_id: Admin.id(current_admin)).order('name ASC')
    @players = Admin.info(current_admin).players.order('name ASC')
  end

  # GET /players/1 or /players/1.json
  def show; end

  # GET /players/new
  def new
    @player = Player.new(losses: 0, wins: 0)
  end

  # GET /players/1/edit
  def edit; end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)
    # need to add admin id for the new player that is being created to indicate ownership of that player information
    # and let this user and only this user have access to that information when querying
    @player.admin_id = Admin.info(current_admin).id

    respond_to do |format|
      if @player.save
        format.html { redirect_to(@player, notice: 'Player was successfully created.') }
        format.json { render(:show, status: :created, location: @player) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @player.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    # no need to udpate admin_id b/c it is already there
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to(@player, notice: 'Player was successfully updated.') }
        format.json { render(:show, status: :ok, location: @player) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @player.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy!
    respond_to do |format|
      format.html { redirect_to(players_url, notice: 'Player was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.where(id: params[:id]).first
  end

  # Only allow a list of trusted parameters through.
  def player_params
    params.require(:player).permit(:name, :losses, :wins, :strengths, :weaknesses, :additional_info)
  end
end

app/helpers/players_helper.rb
# frozen_string_literal: true

module PlayersHelper
end

app/views/players/_back.html.erb
<form class="button_to" method="get" action=<%= players_path %>>
  <button class="btn back-button" id="back" title="Back">
    <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-left-short back-button" viewbox="0 0 16 16">
      <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
    </svg>
    <span class="back-button">Back</span>
  </button>
</form>

app/views/players/_form.html.erb
<%= form_with(model: player, class: "") do |form| %>
<% if player.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(player.errors.count, "error") %>
      prohibited this player from being saved:</h2>

    <ul>
      <% player.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :name, class: 'form-label' %>
  <%= form.text_field :name, class: 'form-control', rows: '3', placeholder: 'Enter Player Name'%>
</div>

<br/>

<div class="row justify-content-center text-center">
  <div class="form-group col-3">
    <%= form.label :wins, class: 'form-label'%>
    <%= form.number_field :wins, class: 'form-control text-center' %>
  </div>
  <div class="form-group col-3">
    <%= form.label :losses, class: 'form-label' %>
    <%= form.number_field :losses, class: 'form-control text-center'%>
  </div>
</div>

<br/>

<div class="form-group">
  <%= form.label :strengths, class: 'form-label' %>
  <%= form.text_area :strengths, class: 'form-control', placeholder: 'What are some strengths?'%>
</div>

<div class="form-group">
  <%= form.label :weaknesses, class: 'form-label'%>
  <%= form.text_area :weaknesses, class: 'form-control', placeholder: 'What are some weaknesses?'%>
</div>

<br/>

<div class="form-group">
  <%= form.label :additional_info, class: 'form-label'%>
  <%= form.text_area :additional_info, class: 'form-control', placeholder: 'Any additional information?'%>
</div>

<br>

<button type='submit' class='btn btn-new'>Submit</button>

<br/>

<% end %>

app/views/players/edit.html.erb
<% if Player.allowed_to_show?(current_admin, @player) %>
  <div class="container show-container">
    <div class="container page-top-margin">
      <%= render 'back'%>
    </div>
    <div class="container text-center">
      <h1>
        Editing
        <%= @player.name %>
      </h1>
    </div>

    <div class="container form-bottom-padding justify-content-center">
      <%= render 'form', player: @player %>
    </div>

  </div>
<% else %>
  <%= render 'layouts/permission_denied'%>
<% end %>

app/views/players/index.html.erb
<div class="container flex-column show-container" style="padding-top: 80px;">
  <div class="text-center">
    <h1>Players</h1>
    <%= button_to "New Player", new_player_path, class: 'btn btn-new', :method => :get, title: "New Player"%>
  </div>

  <br/>

  <div class="container">
    <table class="table table-striped table-bordered table-responsive table-font">
      <thead class="thead-light">
        <tr>
          <th scope="col" class="text-center">Name</th>
          <th scope="col" class="text-center">Wins</th>
          <th scope="col" class="text-center">Losses</th>
          <th scope="col" class="text-center">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @players.each do |player| %>
          <tr class="center-vert-hor cell-pad">
            <td>
              <form class="button_to" method="get" action=<%= player_path(player) %>>
                <button class="btn" id="player-<%= player.id %>" title="Player Name">
                  <span style="font-weight: bold"><%= player.name %></span>
                </button>
              </form>
            </td>
            <td><%= player.wins %></td>
            <td><%= player.losses %></td>
            <td>
              <div class="d-flex center-vert-hor actions justify-content-center">
                <form class="button_to" method="get" action=<%= edit_player_path(player) %>>
                  <button class="btn" id="edit-player-<%= player.id %>" title="Edit">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil edit" viewbox="0 0 16 16">
                      <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                    </svg>
                  </button>
                </form>
                <br><br>
                <a data-method="delete" href=<%= player_path(player) %> data-confirm="Are you sure you want to delete all of <%= player.name %>'s data? This action is irreversible!" class="delete" id="delete-player-<%= player.id %>">
                  <button class="btn" title="Delete">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash delete" viewbox="0 0 16 16">
                      <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                      <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                    </svg>
                  </button>
                </a>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

</div>

app/views/players/new.html.erb
<div class="container show-container">
  <div class="container page-top-margin">
    <%= render 'back'%>
  </div>
  <div class="container text-center">
    <h1>
      New Player
    </h1>
  </div>
  <div class="container form-bottom-padding justify-content-center">
    <%= render 'form', player: @player %>
  </div>
</div>

app/views/players/show.html.erb
<% if Player.allowed_to_show?(current_admin, @player) %>
  <div class="container show-container">

    <div class="container page-top-margin">
      <%= render 'back'%>
    </div>
    <div class="container text-center">
      <h1><%= @player.name %></h1>
    </div>

    <!-- Edit/Delete buttons -->
    <div class="d-flex center-vert-hor actions justify-content-center">
      <form class="button_to" method="get" action=<%= edit_player_path(@player) %>>
        <button class="btn" id="edit-player-<%= @player.id %>" title="Edit">
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil edit" viewbox="0 0 16 16">
            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
          </svg>
        </button>
      </form>
      <a data-method="delete" href=<%= player_path(@player) %> data-confirm="Are you sure you?" class="delete" id="delete-player-<%= @player.id %>">
        <button class="btn" title="Delete">
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash delete" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg>
        </button>
      </a>
    </div>

    <br/>

    <div class="container">
      <div class="row justify-content-center text-center" style="padding: 0 3rem;">
        <div class="container col-3">
          <h5>Wins</h5>
          <h6 id="player-wins" ><%= @player.wins %></h6>
        </div>
        <div class="container col-3">
          <h5>Losses</h5>
          <h6 id="player-losses" ><%= @player.losses %></h6>
        </div>
      </div>

      <br/>

      <div class="container">
        <h5>Strengths</h5>
        <p><%= @player.strengths.size == 0 ? "N/A" : @player.strengths %></p>
        <br/>
        <h5>Weaknesses</h5>
        <p><%= @player.weaknesses.size == 0 ? "N/A" : @player.weaknesses %></p>
        <br/>
        <h5>Additional Information</h5>
        <p><%= @player.additional_info.size == 0 ? "N/A" : @player.additional_info %></p>
      </div>
    </div>

  <div>
<% else %>
  <%= render 'layouts/permission_denied'%>
<% end %>