config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profiles/home'
  get 'profiles/edit'
  get 'profiles/update'
  get 'help/index'
  root to: 'players#index'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  resources :players
  resources :permissions
  resources :permission_users
  resources :images
  resources :events

  get 'profiles/home'
  get 'profiles/edit'
  post 'profiles', to: 'profiles#update', as: :update_profile
  delete 'admins/:admin_id', to: 'admins#destroy', as: :destroy_admin

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  has_one_attached :img

  validates :img, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  validates :caption, presence: true, length: { maximum: 256 }

  def self.exist?(cur_image)
    !cur_image.nil?
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  before_action :set_image, only: %i[show edit update destroy]

  # GET /images or /images.json
  def index
    @images = Image.all.order('created_at DESC')
  end

  # GET /images/1 or /images/1.json
  def show; end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit; end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to(@image, notice: 'Image was successfully created.') }
        format.json { render(:show, status: :created, location: @image) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @image.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to(@image, notice: 'Image was successfully updated.') }
        format.json { render(:show, status: :ok, location: @image) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @image.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy!
    respond_to do |format|
      format.html { redirect_to(images_url, notice: 'Image was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.where(id: params[:id]).first
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:caption, :img)
  end
end

app/helpers/images_helper.rb
# frozen_string_literal: true

module ImagesHelper
end

app/views/images/_back.html.erb
<form class="button_to" method="get" action=<%= images_path %>>
  <button class="btn back-button" id="back">
    <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-left-short back-button" viewbox="0 0 16 16">
      <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
    </svg>
    <span class="back-button">Back</span>
  </button>
</form>

app/views/images/_edit.html.erb
<%= form_with(model: image) do |form| %>
<% if image.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(image.errors.count, "error") %>
      prohibited this player from being saved:</h2>

    <ul>
      <% image.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @image.img.attached? %>
  <div class="align-items-center container">
    <%= image_tag(@image.img, class: "show-image")%>
  </div>
  <br/>
<% end %>

<div class="form-group">
  <%= form.label :caption, class: 'form-label' %>
  <%= form.text_area :caption, class: 'form-control', placeholder: "What's happening?"%>
</div>

<br/>

<button type='submit' class='btn btn-secondary'>Submit</button>

<br/>
<% end %>

app/views/images/_edit_form.html.erb
<%= form_with(model: image) do |form| %>
<% if image.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(image.errors.count, "error") %>
      prohibited this player from being saved:</h2>

    <ul>
      <% image.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @image.img.attached? %>
  <div class="align-items-center container">
    <%= image_tag(@image.img, class: "show-image")%>
  </div>
  <br/>
<% end %>

<div class="form-group">
  <%= form.label :caption, class: 'form-label' %>
  <%= form.text_area :caption, class: 'form-control', placeholder: "What's happening?"%>
</div>

<br/>

<button type='submit' class='btn btn-new'>Submit</button>

<br/>
<% end %>

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
<% if image.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(image.errors.count, "error") %>
      prohibited this player from being saved:</h2>

    <ul>
      <% image.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @image.img.attached? %>
  <div class="align-items-center container">
    <%= image_tag(@image.img, class: "show-image")%>
  </div>
  <br/>
<% end %>

<div class="form-group">
  <%= form.label 'Image', class: 'form-label' %>
  <br/>
  <%= form.file_field :img %>
</div>

<br/>

<div class="form-group">
  <%= form.label :caption, class: 'form-label' %>
  <%= form.text_area :caption, class: 'form-control', placeholder: "What's happening?"%>
</div>

<br/>

<button type='submit' class='btn btn-new'>Submit</button>

<br/>
<% end %>

app/views/images/edit.html.erb
<% if Image.exist?(@image) && Admin.current_user_admin?(current_admin)%>
  <div class="d-flex flex-column align-items-center show-container">
    <div class="container page-top-margin">
      <%= render 'back'%>
    </div>
    <div class="container text-center">
      <h1>
        Update Image
      </h1>
    </div>
    <div class="d-flex form-bottom-padding justify-content-center">
      <br/>
      <%= render 'edit_form', image: @image %>
    </div>
  </div>
<% else %>
  <%= render 'layouts/permission_denied'%>
<% end %>

app/views/images/edit_form.html.erb
<%= form_with(model: image) do |form| %>
<% if image.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(image.errors.count, "error") %>
      prohibited this player from being saved:</h2>

    <ul>
      <% image.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @image.img.attached? %>
  <div class="align-items-center container">
    <%= image_tag(@image.img, class: "show-image")%>
  </div>
  <br/>
<% end %>

<div class="form-group">
  <%= form.label :caption, class: 'form-label' %>
  <%= form.text_area :caption, class: 'form-control', placeholder: "What's happening?"%>
</div>

<br/>

<button type='submit' class='btn btn-secondary'>Submit</button>

<br/>
<% end %>

app/views/images/index.html.erb
<div class="d-flex flex-column align-items-center show-container" style="padding-top: 80px;">
  <h1>Photo Gallery</h1>
  <% if Admin.current_user_admin?(current_admin) %>
    <%= button_to "New Image", new_image_path, class: 'btn btn-new', :method => :get%>
  <% end %>

  <br/>

  <div class="grid-container">
    <div class="grid-cell">
      <% @images.each do |image| %>
        <form class="button_to" method="get" action=<%= image_path(image) %>>
          <button class="btn" id="image-<%= image.id %>">
            <%= image_tag(image.img, class: "gallery-image", alt: "Photo gallery image")%>
          </button>
        </form>
      <% end %>
    </div>
  </div>

  <br/>

</div>

app/views/images/new.html.erb
<% if Admin.current_user_admin?(current_admin) %>
  <div class="container show-container">
    <div class="container page-top-margin">
      <%= render 'back'%>
    </div>
    <div class="container text-center">
      <h1>
        New Image
      </h1>
    </div>
    <div class="d-flex form-bottom-padding justify-content-center">
      <br/>
      <%= render 'form', image: @image %>
    </div>
  </div>
<% else %>
  <%= render 'layouts/permission_denied'%>
<% end %>

app/views/images/show.html.erb
<% if Image.exist?(@image) %>
  <div class="d-flex flex-column align-items-center show-container">
    <div class="container page-top-margin">
      <%= render 'back'%>
    </div>
    <div class="container text-center">
      <h1>
        Photo
      </h1>
    </div>

    <!-- Edit/Delete buttons -->
    <% if Admin.current_user_admin?(current_admin) %>
      <div class="d-flex center-vert-hor actions justify-content-center">
        <form class="button_to" method="get" action=<%= edit_image_path(@image) %>>
          <button class="btn" id="edit-img-<%= @image.id %>" title="Edit">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil edit" viewbox="0 0 16 16">
              <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
            </svg>
          </button>
        </form>
        <a data-method="delete" href=<%= image_path(@image) %> data-confirm="Are you sure you?" class="delete" id="delete-img-<%= @image.id %>">
          <button class="btn" title="Delete">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash delete" viewbox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
              <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
            </svg>
          </button>
        </a>
      </div>
    <% end %>

    <div class="d-flex justify-content-center">
      <% if @image.img.attached? %>
        <div class="align-items-center container">
          <%= image_tag(@image.img, class: "show-image", alt: "Photo gallery image", id: 'id' + @image.id.to_s)%>
        </div>
        <br/>
      <% end %>
    </div>

    <div class="container form-bottom-padding ">
      <div class="form-group">
        <label class="form-label">
          <strong>Caption</strong>
        </label>

        <br/>

        <p><%= @image.caption %></p>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'layouts/permission_denied'%>
<% end %>