config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profiles/home'
  get 'profiles/edit'
  get 'profiles/update'
  get 'help/index'
  root to: 'players#index'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  resources :players
  resources :permissions
  resources :permission_users
  resources :images
  resources :events

  get 'profiles/home'
  get 'profiles/edit'
  post 'profiles', to: 'profiles#update', as: :update_profile
  delete 'admins/:admin_id', to: 'admins#destroy', as: :destroy_admin

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_permission_denied.html.erb
<div class="d-flex justify-content-center flex-column align-items-center text-center" style="height: 100%">
	<h1 style="color: #ff0000">
		PERMISSION DENIED
	</h1>
	<h2>You do not have the permission to acess this page!</h2>
</div>

app/views/layouts/_sidebar.html.erb
<% if current_admin != nil %>
  <header class="header" id="header">
    <div class="header_toggle">
      <i class='bx bx-menu' id="header-toggle"></i>
    </div>

    <div class="dropdown">
      <a class="btn btn-sm dropdown-toggle header_dropdown" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown">
        <img src="<%= current_admin.avatar_url%>" width="40" height="40" class="rounded-circle">
      </a>

      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <li>
          <a class="dropdown-item" href=<%= destroy_admin_session_path %> id="sign-out-nav-bar">Sign Out</a>
        </li>
      </ul>
    </div>
  </header>
<% else %>
  <header class="header" id="header" style="justify-content: end;">
    <div>
      <%= button_to "Sign In", admin_google_oauth2_omniauth_authorize_path, class: 'btn btn-primary'%>
      <div>
  </header>
<% end %>
<% if current_admin != nil %>
  <div class="l-navbar" id="nav-bar">
    <nav class="nav">
      <div class="overflow-auto">
        <div class="nav_list">
          <a href=<%= root_path %> class="nav_logo tab" id="root-tab">
            <i class="fas fa-table-tennis nav_logo-icon"></i>
            <span class="nav_logo-name">Info Tracker</span>
          </a>
        </div>
        <div class="nav_list">
          <a href=<%= players_path %> class="nav_link active tab" id="home-tab">
            <i class="bi bi-house nav_icon"></i>
            <span class="nav_name">Home</span>
          </a>
          <a href=<%= events_path %> class="nav_link tab" id="events-tab">
            <i class="bi bi-calendar4-event nav_icon"></i>
            <span class="nav_name">Events</span>
          </a>
          <a href=<%= images_path %> class="nav_link tab" id="gallery-tab">
            <i class="bi bi-images nav_icon"></i>
            <span class="nav_name">Gallery</span>
          </a>
          <a href='/profiles/home' class="nav_link tab" id="profile-tab">
            <i class='bx bx-user nav_icon'></i>
            <span class="nav_name">Profile</span>
          </a>
          <% if Admin.current_user_admin?(current_admin) %>
            <a href="/permission_users" class="nav_link tab" id="manage-users-tab">
              <i class="bx bx-group nav_icon"></i>
              <span class="nav_name">Manage Users</span>
            </a>
            <a href=<%= help_index_url %> class="nav_link tab" id="help-tab">
              <i class="bi bi-question-circle nav-icon"></i>
              <span class="nav_name">Help</span>
            </a>
          <% end %>
        </div>
      </div>
      <a href=<%= destroy_admin_session_path %> class="nav_link" id="sign-out-side-bar">
        <i class='bx bx-log-out nav_icon'></i>
        <span class="nav_name">Sign Out</span>
      </a>
    </nav>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Table Tennis Info Tracker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <script src="https://kit.fontawesome.com/ae13195a70.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    

    <style>
      .flash__alert {
        color: red;
      }
      .flash__notice {
        color: blue;
      }
      .flash__success {
        color: green;
      }
    </style>
  </head>

  <body id="body-pd">
    <%= render 'layouts/sidebar' %>
    <% if flash.any? %>
      <% flash.each do |key, value| -%>
        <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
      <% end -%>
    <% end %>
    <%= yield %>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
  </body>
</html>